defmodule McEmcommWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :mc_emcomm

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # `secure:` is on wherever the app is served over HTTPS (see
  # :secure_cookies in config/prod.exs). Dev and test run over plain HTTP on
  # localhost, where a browser would drop a Secure cookie outright.
  @session_options [
    store: :cookie,
    key: "_mc_emcomm_key",
    signing_salt: "OKzLTE5q",
    same_site: "Lax",
    secure: Application.compile_env(:mc_emcomm, :secure_cookies, false)
  ]

  # Long polling is disabled as defense in depth for CVE-2026-32689
  # (GHSA-628h-q48j-jr6q); WebSockets are the only LiveView transport.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :mc_emcomm,
    gzip: not code_reloading?,
    only: McEmcommWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Tidewave exposes a dev-only MCP server at /tidewave/mcp for coding agents.
  # It accepts local connections only and is never compiled into other envs.
  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :mc_emcomm
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  plug McEmcommWeb.Plugs.TraceContext

  # The :body_reader keeps the raw request body for webhook signature
  # verification (see McEmcommWeb.Plugs.CacheRawBody).
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {McEmcommWeb.Plugs.CacheRawBody, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug McEmcommWeb.Router
end
