defmodule McEmcommWeb.UserAuth do
  @moduledoc """
  Plugs and LiveView `on_mount` hooks for user authentication, generated by
  `mix phx.gen.auth`: session rotation on login, log-out-everywhere via token
  deletion, and sudo mode for sensitive actions.

  On top of the generated code this module tracks the *pending two-factor
  login*: after a password or magic link succeeds for a user with TOTP
  enabled, the login is parked in the session under `:pending_two_factor`
  until `McEmcommWeb.UserSessionController.verify_two_factor/2` accepts a
  code. The pending map carries no secrets (the session cookie is signed,
  not encrypted): only the user id, the remember-me choice, the flash to
  show on success, a timestamp, and a failed-attempt counter. Because the
  counter lives in the cookie it bounds attempts per cookie rather than per
  user; network-level rate limiting is out of scope here.
  """
  use McEmcommWeb, :verified_routes

  import Plug.Conn
  import Phoenix.Controller

  alias McEmcomm.Accounts
  alias McEmcomm.Accounts.Scope
  alias McEmcomm.Accounts.User
  alias Phoenix.LiveView.Socket

  # Make the remember me cookie valid for 14 days. This should match
  # the session validity setting in UserToken.
  @max_cookie_age_in_days 14
  @remember_me_cookie "_mc_emcomm_web_user_remember_me"
  # The remember-me cookie carries a live session token, so it is marked
  # Secure wherever the app is served over HTTPS (see :secure_cookies in
  # config/prod.exs).
  @remember_me_options [
    sign: true,
    max_age: @max_cookie_age_in_days * 24 * 60 * 60,
    same_site: "Lax",
    secure: Application.compile_env(:mc_emcomm, :secure_cookies, false)
  ]

  # How old the session token should be before a new one is issued. When a request is made
  # with a session token older than this value, then a new session token will be created
  # and the session and remember-me cookies (if set) will be updated with the new token.
  # Lowering this value will result in more tokens being created by active users. Increasing
  # it will result in less time before a session token expires for a user to get issued a new
  # token. This can be set to a value greater than `@max_cookie_age_in_days` to disable
  # the reissuing of tokens completely.
  @session_reissue_age_in_days 7

  # A parked login must finish its two-factor challenge within this window
  # and with fewer than this many wrong codes; otherwise it is discarded and
  # the primary factor has to be presented again.
  @pending_two_factor_max_age_in_seconds 10 * 60
  @pending_two_factor_max_attempts 5

  @doc """
  Logs the user in.

  Redirects to the session's `:user_return_to` path
  or falls back to the `signed_in_path/1`.
  """
  @spec log_in_user(Plug.Conn.t(), User.t(), map()) :: Plug.Conn.t()
  def log_in_user(conn, user, params \\ %{}) do
    user_return_to = get_session(conn, :user_return_to)

    conn
    |> create_or_extend_session(user, params)
    |> delete_session(:user_return_to)
    |> redirect(to: user_return_to || signed_in_path(conn))
  end

  @doc """
  Builds the session payload for a login that still needs a second factor.

  `params` are the login form params (`"remember_me"` is kept); `info` is
  the flash to show once the challenge succeeds.
  """
  @spec build_pending_two_factor(User.t(), map(), String.t()) :: map()
  def build_pending_two_factor(%User{id: user_id}, params, info) when is_binary(info) do
    %{
      "user_id" => user_id,
      "remember_me" => params["remember_me"],
      "info" => info,
      "at" => System.os_time(:second),
      "attempts" => 0
    }
  end

  @doc """
  Parks the login in the session and sends the user to the two-factor
  challenge page.

  The session is deliberately not renewed here: a user re-authenticating for
  sudo mode stays logged in while they complete the challenge, and
  `:user_return_to` survives for `log_in_user/3` afterwards.
  """
  @spec challenge_two_factor(Plug.Conn.t(), User.t(), map(), String.t()) :: Plug.Conn.t()
  def challenge_two_factor(conn, user, params, info) do
    conn
    |> put_session(:pending_two_factor, build_pending_two_factor(user, params, info))
    |> redirect(to: ~p"/users/two-factor")
  end

  @doc """
  Returns the pending two-factor map when it is present and not older than
  the challenge window, otherwise `nil`. Pure, so LiveViews can call it on
  the session map they receive in `mount/3`.
  """
  @spec valid_pending_two_factor(map() | nil) :: map() | nil
  def valid_pending_two_factor(%{"user_id" => _, "at" => at} = pending) when is_integer(at) do
    if System.os_time(:second) - at <= @pending_two_factor_max_age_in_seconds,
      do: pending,
      else: nil
  end

  def valid_pending_two_factor(_), do: nil

  @doc """
  Reads the pending two-factor login from the conn session.
  """
  @spec fetch_pending_two_factor(Plug.Conn.t()) :: {:ok, map()} | :error
  def fetch_pending_two_factor(conn) do
    case valid_pending_two_factor(get_session(conn, :pending_two_factor)) do
      nil -> :error
      pending -> {:ok, pending}
    end
  end

  @doc """
  Records a failed challenge attempt.

  Returns `{:retry, conn}` while attempts remain, or `{:locked, conn}` with
  the pending login discarded once the limit is reached.
  """
  @spec fail_pending_two_factor(Plug.Conn.t()) ::
          {:retry, Plug.Conn.t()} | {:locked, Plug.Conn.t()}
  def fail_pending_two_factor(conn) do
    pending = get_session(conn, :pending_two_factor) || %{}
    attempts = Map.get(pending, "attempts", 0) + 1

    if attempts >= @pending_two_factor_max_attempts do
      {:locked, clear_pending_two_factor(conn)}
    else
      {:retry, put_session(conn, :pending_two_factor, Map.put(pending, "attempts", attempts))}
    end
  end

  @doc """
  Forgets the pending two-factor login.
  """
  @spec clear_pending_two_factor(Plug.Conn.t()) :: Plug.Conn.t()
  def clear_pending_two_factor(conn), do: delete_session(conn, :pending_two_factor)

  @doc """
  Logs the user out.

  It clears all session data for safety. See renew_session.
  """
  @spec log_out_user(Plug.Conn.t()) :: Plug.Conn.t()
  def log_out_user(conn) do
    user_token = get_session(conn, :user_token)
    user_token && Accounts.delete_user_session_token(user_token)

    if live_socket_id = get_session(conn, :live_socket_id) do
      McEmcommWeb.Endpoint.broadcast(live_socket_id, "disconnect", %{})
    end

    conn
    |> renew_session(nil)
    |> delete_resp_cookie(@remember_me_cookie, @remember_me_options)
    |> redirect(to: ~p"/")
  end

  @doc """
  Authenticates the user by looking into the session and remember me token.

  Will reissue the session token if it is older than the configured age.
  """
  @spec fetch_current_scope_for_user(Plug.Conn.t(), keyword()) :: Plug.Conn.t()
  def fetch_current_scope_for_user(conn, _opts) do
    with {token, conn} <- ensure_user_token(conn),
         {user, token_inserted_at} <- Accounts.get_user_by_session_token(token) do
      conn
      |> assign(:current_scope, Scope.for_user(user))
      |> maybe_reissue_user_session_token(user, token_inserted_at)
    else
      nil -> assign(conn, :current_scope, Scope.for_user(nil))
    end
  end

  defp ensure_user_token(conn) do
    if token = get_session(conn, :user_token) do
      {token, conn}
    else
      conn = fetch_cookies(conn, signed: [@remember_me_cookie])

      if token = conn.cookies[@remember_me_cookie] do
        {token, conn |> put_token_in_session(token) |> put_session(:user_remember_me, true)}
      else
        nil
      end
    end
  end

  # Reissue the session token if it is older than the configured reissue age.
  defp maybe_reissue_user_session_token(conn, user, token_inserted_at) do
    token_age = DateTime.diff(DateTime.utc_now(:second), token_inserted_at, :day)

    if token_age >= @session_reissue_age_in_days do
      create_or_extend_session(conn, user, %{})
    else
      conn
    end
  end

  # This function is the one responsible for creating session tokens
  # and storing them safely in the session and cookies. It may be called
  # either when logging in, during sudo mode, or to renew a session which
  # will soon expire.
  #
  # When the session is created, rather than extended, the renew_session
  # function will clear the session to avoid fixation attacks. See the
  # renew_session function to customize this behaviour.
  defp create_or_extend_session(conn, user, params) do
    token = Accounts.generate_user_session_token(user)
    remember_me = get_session(conn, :user_remember_me)

    conn
    |> renew_session(user)
    |> put_token_in_session(token)
    |> maybe_write_remember_me_cookie(token, params, remember_me)
  end

  # Do not renew session if the user is already logged in
  # to prevent CSRF errors or data being lost in tabs that are still open
  defp renew_session(conn, user) when conn.assigns.current_scope.user.id == user.id do
    conn
  end

  # This function renews the session ID and erases the whole
  # session to avoid fixation attacks. If there is any data
  # in the session you may want to preserve after log in/log out,
  # you must explicitly fetch the session data before clearing
  # and then immediately set it after clearing, for example:
  #
  #     defp renew_session(conn, _user) do
  #       delete_csrf_token()
  #       preferred_locale = get_session(conn, :preferred_locale)
  #
  #       conn
  #       |> configure_session(renew: true)
  #       |> clear_session()
  #       |> put_session(:preferred_locale, preferred_locale)
  #     end
  #
  defp renew_session(conn, _user) do
    delete_csrf_token()

    conn
    |> configure_session(renew: true)
    |> clear_session()
  end

  defp maybe_write_remember_me_cookie(conn, token, %{"remember_me" => "true"}, _),
    do: write_remember_me_cookie(conn, token)

  defp maybe_write_remember_me_cookie(conn, token, _params, true),
    do: write_remember_me_cookie(conn, token)

  defp maybe_write_remember_me_cookie(conn, _token, _params, _), do: conn

  defp write_remember_me_cookie(conn, token) do
    conn
    |> put_session(:user_remember_me, true)
    |> put_resp_cookie(@remember_me_cookie, token, @remember_me_options)
  end

  defp put_token_in_session(conn, token) do
    conn
    |> put_session(:user_token, token)
    |> put_session(:live_socket_id, user_session_topic(token))
  end

  @doc """
  Disconnects existing sockets for the given tokens.
  """
  @spec disconnect_sessions([%{required(:token) => binary()}]) :: :ok
  def disconnect_sessions(tokens) do
    Enum.each(tokens, fn %{token: token} ->
      McEmcommWeb.Endpoint.broadcast(user_session_topic(token), "disconnect", %{})
    end)
  end

  defp user_session_topic(token), do: "users_sessions:#{Base.url_encode64(token)}"

  @doc """
  Handles mounting and authenticating the current_scope in LiveViews.

  ## `on_mount` arguments

    * `:mount_current_scope` - Assigns current_scope
      to socket assigns based on user_token, or nil if
      there's no user_token or no matching user.

    * `:require_authenticated` - Authenticates the user from the session,
      and assigns the current_scope to socket assigns based
      on user_token.
      Redirects to login page if there's no logged user.

  ## Examples

  Use the `on_mount` lifecycle macro in LiveViews to mount or authenticate
  the `current_scope`:

      defmodule McEmcommWeb.PageLive do
        use McEmcommWeb, :live_view

        on_mount {McEmcommWeb.UserAuth, :mount_current_scope}
        ...
      end

  Or use the `live_session` of your router to invoke the on_mount callback:

      live_session :authenticated, on_mount: [{McEmcommWeb.UserAuth, :require_authenticated}] do
        live "/profile", ProfileLive, :index
      end
  """
  @spec on_mount(
          :mount_current_scope | :require_authenticated | :require_sudo_mode,
          map(),
          map(),
          Socket.t()
        ) ::
          {:cont, Socket.t()} | {:halt, Socket.t()}
  def on_mount(:mount_current_scope, _params, session, socket) do
    {:cont, mount_current_scope(socket, session)}
  end

  def on_mount(:require_authenticated, _params, session, socket) do
    socket = mount_current_scope(socket, session)

    if socket.assigns.current_scope && socket.assigns.current_scope.user do
      {:cont, socket}
    else
      socket =
        socket
        |> Phoenix.LiveView.put_flash(:error, "You must log in to access this page.")
        |> Phoenix.LiveView.redirect(to: ~p"/users/log-in")

      {:halt, socket}
    end
  end

  def on_mount(:require_sudo_mode, _params, session, socket) do
    socket = mount_current_scope(socket, session)

    if Accounts.sudo_mode?(socket.assigns.current_scope.user, -10) do
      {:cont, socket}
    else
      socket =
        socket
        |> Phoenix.LiveView.put_flash(:error, "You must re-authenticate to access this page.")
        |> Phoenix.LiveView.redirect(to: ~p"/users/log-in")

      {:halt, socket}
    end
  end

  defp mount_current_scope(socket, session) do
    Phoenix.Component.assign_new(socket, :current_scope, fn ->
      {user, _} =
        if user_token = session["user_token"] do
          Accounts.get_user_by_session_token(user_token)
        end || {nil, nil}

      Scope.for_user(user)
    end)
  end

  @doc """
  Returns the path to redirect to after log in.

  Called with a `Plug.Conn` from `log_in_user/3` and with a
  `Phoenix.LiveView.Socket` from LiveViews that bounce an already-signed-in
  visitor; only the conn carries a `current_scope`, so a socket always falls
  through to the root path.
  """
  # the user was already logged in, redirect to settings
  @spec signed_in_path(Plug.Conn.t() | Socket.t()) :: String.t()
  def signed_in_path(%Plug.Conn{assigns: %{current_scope: %Scope{user: %User{}}}}) do
    ~p"/users/settings"
  end

  def signed_in_path(_), do: ~p"/"

  @doc """
  Plug for routes that require the user to be authenticated.
  """
  @spec require_authenticated_user(Plug.Conn.t(), keyword()) :: Plug.Conn.t()
  def require_authenticated_user(conn, _opts) do
    if conn.assigns.current_scope && conn.assigns.current_scope.user do
      conn
    else
      conn
      |> put_flash(:error, "You must log in to access this page.")
      |> maybe_store_return_to()
      |> redirect(to: ~p"/users/log-in")
      |> halt()
    end
  end

  defp maybe_store_return_to(%{method: "GET"} = conn) do
    put_session(conn, :user_return_to, current_path(conn))
  end

  defp maybe_store_return_to(conn), do: conn
end
