import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :mc_emcomm, McEmcommWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :mc_emcomm, McEmcommWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # Fly health checks arrive over plain HTTP on the private network.
      paths: ["/healthz/live", "/healthz/ready"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Production is HTTPS-only (force_ssl above), so cookies carry the Secure
# attribute and are never sent over a plaintext request.
config :mc_emcomm, :secure_cookies, true

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
